default:
  image: grifart/php7.4-with-gulp-and-all-php-modules

stages:
  - build
  - test


build.composer:
  stage: build

  script:
    - composer install --ansi --no-interaction --prefer-dist

  artifacts:
    expire_in: 2 days
    paths:
      - vendor


test.tests:
  stage: test

  dependencies: [build.composer]
  script:
    - composer run tester


test.phpstan:
  stage: test

  dependencies: [build.composer]
  script:
    - composer run phpstan


test.linter:
  stage: test

  dependencies: [build.composer]
  script:
    - composer run syntax-check
