stages:
  - build
  - test


build.composer:
  stage: build
  tags: [grifart/php7.1-with-gulp-and-all-php-modules]

  script:
    - composer install --ansi --no-interaction --prefer-dist

  artifacts:
    expire_in: 2 days
    paths:
      - vendor


test.tests:
  stage: test
  tags: [grifart/php7.1-with-gulp-and-all-php-modules]

  dependencies: [build.composer]
  script:
    - composer run tester


test.phpstan:
  stage: test
  tags: [grifart/php7.1-with-gulp-and-all-php-modules]

  dependencies: [build.composer]
  script:
    - composer run phpstan


test.linter:
  stage: test
  tags: [grifart/php7.1-with-gulp-and-all-php-modules]

  dependencies: [build.composer]
  script:
    - composer run syntax-check
