stages:
  - install
  - test


.install:
  stage: install
  interruptible: true
  script:
    - composer install --ansi --no-interaction --prefer-dist
  artifacts:
    expire_in: 2 days
    paths:
      - vendor/

install.php82:
  extends: .install
  image: grifart/php8.2-with-all-modules-and-various-tools

install.php83:
  extends: .install
  image: grifart/php8.3-with-all-modules-and-various-tools

install.php84:
  extends: .install
  image: grifart/php8.4-with-all-modules-and-various-tools


.test:
  stage: test
  interruptible: true
  script:
    - composer run tester

test.php82:
  extends: .test
  image: grifart/php8.2-with-all-modules-and-various-tools
  dependencies: [ install.php82 ]

test.php83:
  extends: .test
  image: grifart/php8.3-with-all-modules-and-various-tools
  dependencies: [ install.php83 ]

test.php84:
  extends: .test
  image: grifart/php8.4-with-all-modules-and-various-tools
  dependencies: [ install.php84 ]


phpstan:
  stage: test
  image: grifart/php8.4-with-all-modules-and-various-tools
  dependencies: [ install.php84 ]
  script: composer run phpstan


linter:
  stage: test
  image: grifart/php8.4-with-all-modules-and-various-tools
  dependencies: [ install.php84 ]
  script: composer run syntax-check
